# Generated by Django 5.0.3 on 2024-03-31 08:39

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id_board', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('id_status_task', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'status_task',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id_block', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('id_board', models.ForeignKey(db_column='id_board', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='managment.board')),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField()),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='managment.block')),
                ('id_status_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='managment.statustask')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='managment.task')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='UserBoard',
            fields=[
                ('id_user_board', models.AutoField(primary_key=True, serialize=False)),
                ('id_board', models.ForeignKey(db_column='id_board', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='managment.board')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
                ('id_user_role', models.ForeignKey(db_column='id_user_role', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='managment.userrole')),
            ],
            options={
                'db_table': 'user_board',
            },
        ),
    ]
