# Generated by Django 5.0.3 on 2024-04-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='id_block',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='id_board',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='id_comment',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='statustask',
            old_name='id_status_task',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id_task',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userboard',
            old_name='id_user_board',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='id_role',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
