# Generated by Django 5.0.3 on 2024-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_rename_id_block_block_id_rename_id_board_board_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='userboard',
            name='id_board',
        ),
        migrations.RemoveField(
            model_name='userboard',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='userboard',
            name='id_user_role',
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(to='managment.userboard'),
        ),
        migrations.AddField(
            model_name='user',
            name='boards',
            field=models.ManyToManyField(to='managment.userboard'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='boards',
            field=models.ManyToManyField(to='managment.userboard'),
        ),
        migrations.AlterModelTable(
            name='block',
            table=None,
        ),
        migrations.AlterModelTable(
            name='board',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='statustask',
            table=None,
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userboard',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userrole',
            table=None,
        ),
    ]
