# Generated by Django 5.0.3 on 2024-04-23 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_alter_user_options_remove_userboard_id_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='boards',
        ),
        migrations.AddField(
            model_name='userboard',
            name='id_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='managment.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userboard',
            name='id_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userboard',
            name='id_user_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='managment.userrole'),
            preserve_default=False,
        ),
    ]
