# Generated by Django 5.0.3 on 2024-04-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_remove_board_users_remove_user_boards_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
