# Generated by Django 5.0.3 on 2024-05-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0009_userrole_id_board_alter_userrole_deleting_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='add_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='delete_members',
            field=models.BooleanField(default=False),
        ),
    ]
