# Generated by Django 5.0.3 on 2024-05-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0010_userrole_add_members_userrole_delete_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='edit_member_role',
            field=models.BooleanField(default=False),
        ),
    ]
