# Generated by Django 5.0.3 on 2024-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0012_rename_edit_member_role_userrole_edit_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='userboard',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
