# Generated by Django 5.0.3 on 2024-05-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0013_userboard_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='editing_board',
            field=models.BooleanField(default=True),
        ),
    ]
