# Generated by Django 5.0.3 on 2024-05-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0014_userrole_editing_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustask',
            name='id_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_tasks', to='managment.board'),
            preserve_default=False,
        ),
    ]
