# Generated by Django 5.0.3 on 2024-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0015_statustask_id_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='creating_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='deleting_all_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='deleting_ur_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='editing_ur_comment',
            field=models.BooleanField(default=True),
        ),
    ]
