# Generated by Django 5.0.3 on 2024-05-18 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0016_userrole_creating_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='creating_comment',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 18)),
        ),
    ]
